# Generated by Django 5.2 on 2025-05-08 12:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип груза')),
            ],
            options={
                'verbose_name': 'Тип груза',
                'verbose_name_plural': 'Типы груза',
            },
        ),
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тип упаковки')),
            ],
            options={
                'verbose_name': 'Тип упаковки',
                'verbose_name_plural': 'Типы упаковки',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='TransportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_plate', message='Номер должен быть в формате 1 буква, 3 цифры, 2 буквы (буквы из набора А,В,Е,К,М,Н,О,Р,С,Т,У,Х).', regex='^[АВЕКМНОРСТУХ]\\d{3}[АВЕКМНОРСТУХ]{2}$')], verbose_name='Номер транспорта')),
            ],
            options={
                'verbose_name': 'Номер транспорта',
                'verbose_name_plural': 'Номера транспорта',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_number', models.CharField(max_length=20, verbose_name='Номер транспорта (ручной ввод)')),
                ('departure_datetime', models.DateTimeField(verbose_name='Время отправления')),
                ('arrival_datetime', models.DateTimeField(verbose_name='Время доставки')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Дистанция, км')),
                ('media_file', models.FileField(help_text='PDF или изображение', upload_to='deliveries/media/', verbose_name='Медиафайл')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_transit', 'В пути'), ('delivered', 'Доставлено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус доставки')),
                ('technical_state', models.CharField(choices=[('ok', 'Исправно'), ('nok', 'Неисправно')], default='ok', max_length=3, verbose_name='Техническое состояние')),
                ('cargo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='deliveries.cargotype', verbose_name='Тип груза')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deliveries.packagingtype', verbose_name='Упаковка')),
                ('services', models.ManyToManyField(related_name='deliveries', to='deliveries.service', verbose_name='Услуги')),
                ('transport_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deliveries.transportmodel', verbose_name='Модель транспорта')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
                'ordering': ['-departure_datetime'],
            },
        ),
    ]
