# Generated by Django 5.2 on 2025-05-08 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='transport_number',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='media_file',
            field=models.FileField(help_text='PDF или изображение', upload_to='deliveries/media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Допустимые форматы: PDF, JPG, JPEG, PNG.')], verbose_name='Медиафайл'),
        ),
    ]
